### ISSUE TITLE
Weird autoimport results

### ISSUE THREAD

**Issue by zhou13** [alexpasmantier/pymple.nvim#50] opened 2024-10-03 20:19 UTC
I am playing with the pymple's autoimport feature. It shows weird results:
<img width="750" alt="Screenshot 2024-10-03 at 4 17 04 PM" src="https://github.com/user-attachments/assets/e2018d9d-2b6e-4fc6-9f76-129a7168799c">

I am not sure if this is intended. I am on a Mac so `.Users.yichaozhou.Sources.autoimport.autoimport.entrypoints.cli` is an absolute directory. I think these kinds of results are not very helpful. My current directory is at `/Users/yichaozhou/Sources/autoimport`. I think it should either not show these results or trim against the current directory.

**Comment by alexpasmantier** [comment] 2024-10-04 20:24
Thanks for the feedback, can you provide a minimal file structure to reproduce that behavior?

Will try to investigate that over the week-end.

Cheers

**Comment by alexpasmantier** [comment] 2024-10-05 18:26
FWI I temporarily added a fix so that these results don't come up anymore while I investigate the reason they come up in the first place.

**Comment by zhou13** [comment] 2024-10-06 19:55
Thank you for the update.  It seems that this workaround the problem for me.  Add some reproduce way:

```
git clone https://github.com/lyz-code/autoimport.git
cd autoimport
nvim src/autoimport/__main__.py
```
Then delete the import line and execute autoimport on the line `cli()`.

**Comment by windowsrefund** [comment] 2024-11-22 16:56
Seeing this behavior as well regarding the absolute paths.

**Comment by dimtsi** [comment] 2024-11-26 06:07
Same thing is happening to me when using the `resolve-import-under-cursor` functionality. It imports absolute paths instead of `from <PROJECT_ROOT>....` statements

**Comment by domizianooo** [comment] 2024-11-28 18:50
> Same thing is happening to me when using the `resolve-import-under-cursor` functionality. It imports absolute paths instead of `from <PROJECT_ROOT>....` statements

Same here

**Comment by alexpasmantier** [comment] 2024-11-28 22:28
Should now be fixed by updating pymple to its latest version.

Sorry for the inconvenience 🙏🏻

**Comment by domizianooo** [comment] 2024-11-30 19:08
> Should now be fixed by updating pymple to its latest version.
> 
> Sorry for the inconvenience 🙏🏻

It's working correctly for me now, thanks!

**Closed as completed** 2024-11-30 20:30 UTC
